name: my_web_app
description: ARTA ADMIN Login Portal

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^5.0.0
  flutter_svg: ^1.1.1
  image_picker: ^0.8.7
  shared_preferences: ^2.1.0
  supabase_flutter: ^2.4.0
  uuid: ^4.0.0
  mobile_scanner: ^3.5.6
  permission_handler: ^11.0.1
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/background.jpeg
    - assets/city_logo.png
    - assets/arta_logo.png
    - assets/logo_heading.png
    - assets/logo_headingblk.png
    - assets/emoticons/